# Generated by Django 5.1.2 on 2024-10-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auten", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
